name: angular_cli
version: 0.1.1
authors:
- Tianfei Zhu <tianfei@google.com>
- Jing Bian <jingbian@google.com>
- Jonah Williams <jonahwilliams@google.com>
homepage: https://github.com/google/angular_cli
description: Scaffolding tool for AngularDart
environment:
  sdk: '>=1.24.0 <2.0.0'
executables:
  ngdart:
dependencies:
  analyzer: ^0.30.0
  ansicolor: ^0.0.9
  args: ^0.13.7
  html: ^0.13.2
  mustache: ^0.2.5
  logging: ^0.11.3
  path: ^1.4.2
  resource: ^2.1.2
dev_dependencies:
  test: ^0.12.21
